const codes = {
  1000: 'REGISTRATION VALIDATION ERROR',
  1001: 'REGISTRATION ERROR',
  1002: 'LOGIN VALIDATION ERROR',
  1003: 'LOGIN ERROR',
  1004: 'PASSWORD VALIDATION ERROR'
}

export default codes;